name: CI

on:
  push:
    branches:
      - 'dev/**'
      - 'feature/**'
    tags:
      - v*.*.*
  workflow_dispatch:

env:
  ORIGINAL_PROJECT: "noeru-desu/Real-ESRGAN-GUI"
  PROGRAM_NAME: "Real ESRGAN GUI Launcher"
  BUILD_ENV: "win64-nuitka-msvc-14.2"

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}
      - name: Clone repo
        uses: actions/checkout@v2
      - name: 'Set up Developer Command Prompt'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Get tag name
        if: startsWith(github.ref, 'refs/tags/') && github.repository == env.ORIGINAL_PROJECT
        shell: cmd
        id: get_tag_name
        run: |
          setlocal enabledelayedexpansion
          set ver=${{ github.ref_name }}
          set "ver=!ver:v=!"
          echo "VERSION_TAG_SHORT=!ver!" >> $GITHUB_ENV
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/.github/workflows/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install pip --upgrade
          pip install colorlog zstandard nvidia-ml-py
          pip install -U "https://wxpython.org/Phoenix/snapshot-builds/wxPython-4.1.2a1.dev5293+b2199e29-cp310-cp310-win_amd64.whl"
          pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"
      - name: Cache Nuitka
        uses: actions/cache@v2
        with:
          path: |
            C:/Users/runneradmin/AppData/Local/Nuitka/Nuitka/depends
          key: ${{ env.ORIGINAL_PROJECT }}-nuitka
      - name: Build artifacts
        shell: cmd
        run: |
          mkdir nuitka
          nuitka --python-flag=-OO --msvc=latest --lto=yes --onefile --assume-yes-for-downloads --plugin-enable=anti-bloat,pkg-resources --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --include-module=wx._xml --output-dir=nuitka Real_ESRGAN_gui.py
      - name: Basic tests
        shell: cmd
        run: |
          "./nuitka/Real_ESRGAN_gui.exe" +test
      - name: Rename release exe
        if: startsWith(github.ref, 'refs/tags/') && github.repository == env.ORIGINAL_PROJECT
        shell: cmd
        run: |
          copy "./nuitka/Real_ESRGAN_gui.exe" "./"
          ren "./Real_ESRGAN_gui.exe" "./Real_ESRGAN_gui_${{ env.VERSION_TAG_SHORT }}.exe"
      - name: Draft release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == env.ORIGINAL_PROJECT
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ env.PROGRAM_NAME }} ${{ env.VERSION_TAG_SHORT }}
          body: |
            ## 新增
            * 
            * 
            ## 修改与优化
            * 
            * 
            ## 修复
            * 
            * 
          files: |
            RealESRGAN_gui_${{ env.VERSION_TAG_SHORT }}.exe
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD_ENV }}-build.${{ env.GITHUB_RUN_NUMBER }}
          path: nuitka/Real_ESRGAN_gui.exe
