name: CI

on: [ push, pull_request ]

jobs:
  Build-by-Pyinstaller:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: amd64-win64-pyinstaller,  os: windows-latest, A: x64, bit: 64 }
          # - { name: i386-win32-gui-pyinstaller-packaged,  os: windows-latest, A: x86, bit: 32 }
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download UPX
      uses: i3h/download-release-asset@v1.3.2
      with:
        owner: upx
        repo: upx
        tag: latest
        file: /upx-[0-9.]+-win${{ matrix.bit }}.zip/
        path: ./
    - name: Unzip UPX
      run: |
        Expand-Archive -Path ./upx-*.zip -DestinationPath ./
        Move-Item ./upx-*/upx.exe ./
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      shell: cmd
      run: |
        pip install pyinstaller colorlog nvidia-ml-py
        pip install -U "https://wxpython.org/Phoenix/snapshot-builds/wxPython-4.1.2a1.dev5268+fcf49322-cp310-cp310-win_amd64.whl"
    - name: Build artifacts
      shell: cmd
      run: |
        mkdir unpackaged
        mkdir packaged
        pyinstaller -D --distpath ./unpackaged Real_ESRGAN_gui.py
        pyinstaller -F --distpath ./packaged Real_ESRGAN_gui.py
    - name: Basic tests
      shell: cmd
      run: |
        cd packaged
        Real_ESRGAN_gui.exe +test
    - name: Upload unpackaged artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.name }}-unpackaged
        path: unpackaged
    - name: Upload packaged artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.name }}-packaged
        path: packaged
  Build-by-Nuitka:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: amd64-win64-nuitka-msvc-14.2,  os: windows-latest, C: msvc-14.2-x64, A: x64 }
          # - { name: i386-win32-nuitka-msvc-14.2,  os: windows-latest, C: msvc-14.2-x86, A: x86 }
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Set up Developer Command Prompt'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.A }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      shell: cmd
      run: |
        pip install colorlog zstandard nvidia-ml-py
        pip install -U "https://wxpython.org/Phoenix/snapshot-builds/wxPython-4.1.2a1.dev5268+fcf49322-cp310-cp310-win_amd64.whl"
        pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"
    - name: Build artifacts
      shell: cmd
      run: |
        mkdir nuitka
        mkdir unpackaged
        mkdir packaged
        nuitka --python-flag=-OO --msvc=latest --lto=yes --onefile --assume-yes-for-downloads --plugin-enable=anti-bloat,pkg-resources --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --include-module=wx._xml --output-dir=nuitka Real_ESRGAN_gui.py
    - name: Basic tests
      shell: cmd
      run: |
        cd nuitka
        (xcopy /y /s /h .\Real_ESRGAN_gui.dist\* ..\unpackaged) & (copy .\*.exe ..\packaged) & (rd /s /q .\Real_ESRGAN_gui.dist) & ..\packaged\Real_ESRGAN_gui.exe +test
    - name: Upload unpackaged artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.name }}-unpackaged
        path: unpackaged
    - name: Upload packaged artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.name }}-packaged
        path: packaged
