name: CI

on:
  push:
    branches:
      - 'dev/**'
    tags:
      - v*.*.*
  workflow_dispatch:

env:
  ORIGINAL_PROJECT: "noeru-desu/Real-ESRGAN-GUI"
  BUILD_ENV: "amd64-win64-nuitka-msvc-14.2"

jobs:
  build:
    name: Build exe
    runs-on: windows-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Get tag name
        if: startsWith(github.ref, 'refs/tags/') && github.repository == env.ORIGINAL_PROJECT
        id: get_tag_name
        run: |
          version_tag=${GITHUB_REF/refs\/tags\//}
          version_tag_short=`echo $version_tag | awk 'NR==1,/v/{sub(/v/, "");print}'`
          echo "VERSION_TAG=$version_tag" >> $GITHUB_ENV
          echo "VERSION_TAG_SHORT=$version_tag_short" >> $GITHUB_ENV
      - name: 'Set up Developer Command Prompt'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Upgrade pip
        run: pip install pip --upgrade
      - name: Install dependencies
        run: |
          pip install colorlog zstandard nvidia-ml-py
          pip install -U "https://wxpython.org/Phoenix/snapshot-builds/wxPython-4.1.2a1.dev5292+77fa6cf8-cp310-cp310-win_amd64.whl"
          pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"
      - name: Build artifacts
        shell: cmd
        run: |
          mkdir nuitka
          mkdir packaged
          nuitka --python-flag=-OO --msvc=latest --lto=yes --onefile --assume-yes-for-downloads --plugin-enable=anti-bloat,pkg-resources --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --include-module=wx._xml --output-dir=nuitka Real_ESRGAN_gui.py
      - name: Basic tests
        run: |
          cp nuitka/Real_ESRGAN_gui.exe Real_ESRGAN_gui.exe
      - name: Deal with release exe
        if: startsWith(github.ref, 'refs/tags/') && github.repository == env.ORIGINAL_PROJECT
        run: |
          cp Real_ESRGAN_gui.exe RealESRGAN_gui_$VERSION_TAG_SHORT.exe
          sha1=`sha1sum Real_ESRGAN_gui.exe | awk '{ print toupper($1) }'`
          sha256=`sha256sum Real_ESRGAN_gui.exe | awk '{ print toupper($1) }'`
          echo "EXE_SHA1=$sha1" >> $GITHUB_ENV
          echo "EXE_SHA256=$sha256" >> $GITHUB_ENV
      - name: Draft release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == env.ORIGINAL_PROJECT
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: ${{ env.VERSION_TAG }}
          body: |
            ## 新增
            * 
            * 
            ## 修改与优化
            * 
            * 
            ## 修复
            * 
            * 
            
            ```
            SHA-1: ${{ env.EXE_SHA1 }}
            SHA-256: ${{ env.EXE_SHA256 }}
            ```
          files: |
            RealESRGAN_gui_${{env.VERSION_TAG_SHORT}}.exe
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD_ENV }}
          path: packaged
